# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.command_templates_api import CommandTemplatesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommandTemplatesApi(unittest.TestCase):
    """CommandTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.command_templates_api.CommandTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_command_template_api2_command_templates_post(self):
        """Test case for create_command_template_api2_command_templates_post

        Create Command Template  # noqa: E501
        """
        pass

    def test_delete_command_template_api2_command_templates_command_template_id_delete(self):
        """Test case for delete_command_template_api2_command_templates_command_template_id_delete

        Delete Command Template  # noqa: E501
        """
        pass

    def test_get_command_template_api2_command_templates_command_template_id_get(self):
        """Test case for get_command_template_api2_command_templates_command_template_id_get

        Get Command Template  # noqa: E501
        """
        pass

    def test_get_command_templates_api2_command_templates_get(self):
        """Test case for get_command_templates_api2_command_templates_get

        Get Command Templates  # noqa: E501
        """
        pass

    def test_update_command_template_api2_command_templates_command_template_id_put(self):
        """Test case for update_command_template_api2_command_templates_command_template_id_put

        Update Command Template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
