# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.channel_gambling_api import ChannelGamblingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelGamblingApi(unittest.TestCase):
    """ChannelGamblingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.channel_gambling_api.ChannelGamblingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_roulette_settings_api2_channels_channel_id_roulette_settings_get(self):
        """Test case for get_roulette_settings_api2_channels_channel_id_roulette_settings_get

        Get Roulette Settings  # noqa: E501
        """
        pass

    def test_get_slots_settings_api2_channels_channel_id_slots_settings_get(self):
        """Test case for get_slots_settings_api2_channels_channel_id_slots_settings_get

        Get Slots Settings  # noqa: E501
        """
        pass

    def test_update_roulette_settings_api2_channels_channel_id_roulette_settings_put(self):
        """Test case for update_roulette_settings_api2_channels_channel_id_roulette_settings_put

        Update Roulette Settings  # noqa: E501
        """
        pass

    def test_update_slots_settings_api2_channels_channel_id_slots_settings_put(self):
        """Test case for update_slots_settings_api2_channels_channel_id_slots_settings_put

        Update Slots Settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
