# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.channel_api import ChannelApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelApi(unittest.TestCase):
    """ChannelApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.channel_api.ChannelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_channel_api2_channels_post(self):
        """Test case for create_channel_api2_channels_post

        Create Channel  # noqa: E501
        """
        pass

    def test_delete_channel_api2_channels_channel_id_delete(self):
        """Test case for delete_channel_api2_channels_channel_id_delete

        Delete Channel  # noqa: E501
        """
        pass

    def test_get_channel_api2_channels_channel_id_get(self):
        """Test case for get_channel_api2_channels_channel_id_get

        Get Channel  # noqa: E501
        """
        pass

    def test_get_channels_api2_channels_get(self):
        """Test case for get_channels_api2_channels_get

        Get Channels  # noqa: E501
        """
        pass

    def test_get_channels_api2_global_channels_get(self):
        """Test case for get_channels_api2_global_channels_get

        Get Channels  # noqa: E501
        """
        pass

    def test_update_channel_api2_channels_channel_id_put(self):
        """Test case for update_channel_api2_channels_channel_id_put

        Update Channel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
