# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.chat_api import ChatApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.chat_api.ChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_emulate_channel_chat_message_route_api2_channels_channel_id_chat_messages_emulate_post(self):
        """Test case for emulate_channel_chat_message_route_api2_channels_channel_id_chat_messages_emulate_post

        Emulate Channel Chat Message Route  # noqa: E501
        """
        pass

    def test_emulate_chat_event_progress_api2_channels_channel_id_chat_events_emulate_progress_post(self):
        """Test case for emulate_chat_event_progress_api2_channels_channel_id_chat_events_emulate_progress_post

        Emulate Chat Event Progress  # noqa: E501
        """
        pass

    def test_get_chat_events_api2_channels_channel_id_chat_events_get(self):
        """Test case for get_chat_events_api2_channels_channel_id_chat_events_get

        Get Chat Events  # noqa: E501
        """
        pass

    def test_get_chat_messages_api2_channels_channel_id_chat_messages_get(self):
        """Test case for get_chat_messages_api2_channels_channel_id_chat_messages_get

        Get Chat Messages  # noqa: E501
        """
        pass

    def test_get_emotes_api2_chat_emotes_get(self):
        """Test case for get_emotes_api2_chat_emotes_get

        Get Emotes  # noqa: E501
        """
        pass

    def test_get_random_chat_messages_for_chat_preview_api2_channels_channel_id_random_chat_messages_get(self):
        """Test case for get_random_chat_messages_for_chat_preview_api2_channels_channel_id_random_chat_messages_get

        Get Random Chat Messages For Chat Preview  # noqa: E501
        """
        pass

    def test_send_chat_message_api2_chat_messages_post(self):
        """Test case for send_chat_message_api2_chat_messages_post

        Send Chat Message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
