from enum import Enum, IntEnum
from typing import Literal
from pydantic import RootModel, Field
from .base import SynchraBaseModel

class AccessLevel(IntEnum):
    PUBLIC = 0        # Label: Anyone, Permissions: []
    SUB = 1           # Label: Sub, Permissions: []
    VIP = 2           # Label: VIP, Permissions: []
    MOD = 7           # Label: Mod, Permissions: [Read Activity Feed, Use moderation tools]
    EDITOR = 100      # Label: Editor, Permissions: [Manage Commands, Timers, Filters, Quotes, Point Settings, Giveaways, Viewer Queue, Stream Widgets, Update Title, Run Ads, Read Stats]
    ADMIN = 200       # Label: Admin, Permissions: [Manage Integrations, Manage User Access]
    OWNER = 500       # Label: Owner, Permissions: []
    GLOBAL_ADMIN = 1000 # Internal developer level

class Provider(Enum):
    twitch = 'twitch'
    discord = 'discord'
    youtube = 'youtube'
    spotify = 'spotify'
    tiktok = 'tiktok'
    kick = 'kick'
    field_7tv = '7tv'
    betterttv = 'betterttv'
    streamelements = 'streamelements'
    streamlabs = 'streamlabs'

class ProviderList(RootModel[list[Provider | Literal['all']]]):
    root: list[Provider | Literal['all']] = Field(..., title='Provider')

class SubscriptionStatus(Enum):
    active = 'ACTIVE'
    cancelled = 'CANCELLED'
    expired = 'EXPIRED'
    trialing = 'TRIALING'

class Subscription(Enum):
    pro_plus = 'pro_plus'
    pro = 'pro'
    none = 'none'

class CountCurrency(Enum):
    aed = 'AED'
    afn = 'AFN'
    all = 'ALL'
    amd = 'AMD'
    aoa = 'AOA'
    ars = 'ARS'
    aud = 'AUD'
    awg = 'AWG'
    azn = 'AZN'
    bam = 'BAM'
    bbd = 'BBD'
    bdt = 'BDT'
    bhd = 'BHD'
    bif = 'BIF'
    bmd = 'BMD'
    bnd = 'BND'
    bob = 'BOB'
    bov = 'BOV'
    brl = 'BRL'
    bsd = 'BSD'
    btn = 'BTN'
    bwp = 'BWP'
    byn = 'BYN'
    bzd = 'BZD'
    cad = 'CAD'
    cdf = 'CDF'
    che = 'CHE'
    chf = 'CHF'
    chw = 'CHW'
    clf = 'CLF'
    clp = 'CLP'
    cny = 'CNY'
    cop = 'COP'
    cou = 'COU'
    crc = 'CRC'
    cup = 'CUP'
    cve = 'CVE'
    czk = 'CZK'
    djf = 'DJF'
    dkk = 'DKK'
    dop = 'DOP'
    dzd = 'DZD'
    egp = 'EGP'
    ern = 'ERN'
    etb = 'ETB'
    eur = 'EUR'
    fjd = 'FJD'
    fkp = 'FKP'
    gbp = 'GBP'
    gel = 'GEL'
    ghs = 'GHS'
    gip = 'GIP'
    gmd = 'GMD'
    gnf = 'GNF'
    gtq = 'GTQ'
    gyd = 'GYD'
    hkd = 'HKD'
    hnl = 'HNL'
    htg = 'HTG'
    huf = 'HUF'
    idr = 'IDR'
    ils = 'ILS'
    inr = 'INR'
    iqd = 'IQD'
    irr = 'IRR'
    isk = 'ISK'
    jmd = 'JMD'
    jod = 'JOD'
    jpy = 'JPY'
    kes = 'KES'
    kgs = 'KGS'
    khr = 'KHR'
    kmf = 'KMF'
    kpw = 'KPW'
    krw = 'KRW'
    kwd = 'KWD'
    kyd = 'KYD'
    kzt = 'KZT'
    lak = 'LAK'
    lbp = 'LBP'
    lkr = 'LKR'
    lrd = 'LRD'
    lsl = 'LSL'
    lyd = 'LYD'
    mad = 'MAD'
    mdl = 'MDL'
    mga = 'MGA'
    mkd = 'MKD'
    mmk = 'MMK'
    mnt = 'MNT'
    mop = 'MOP'
    mru = 'MRU'
    mur = 'MUR'
    mvr = 'MVR'
    mwk = 'MWK'
    mxn = 'MXN'
    mxv = 'MXV'
    myr = 'MYR'
    mzn = 'MZN'
    nad = 'NAD'
    ngn = 'NGN'
    nio = 'NIO'
    nok = 'NOK'
    npr = 'NPR'
    nzd = 'NZD'
    omr = 'OMR'
    pab = 'PAB'
    pen = 'PEN'
    pgk = 'PGK'
    php = 'PHP'
    pkr = 'PKR'
    pln = 'PLN'
    pyg = 'PYG'
    qar = 'QAR'
    ron = 'RON'
    rsd = 'RSD'
    rub = 'RUB'
    rwf = 'RWF'
    sar = 'SAR'
    sbd = 'SBD'
    scr = 'SCR'
    sdg = 'SDG'
    sek = 'SEK'
    sgd = 'SGD'
    shp = 'SHP'
    sle = 'SLE'
    sos = 'SOS'
    srd = 'SRD'
    ssp = 'SSP'
    stn = 'STN'
    svc = 'SVC'
    syp = 'SYP'
    szl = 'SZL'
    thb = 'THB'
    tjs = 'TJS'
    tmt = 'TMT'
    tnd = 'TND'
    top = 'TOP'
    try_ = 'TRY'
    ttd = 'TTD'
    twd = 'TWD'
    tzs = 'TZS'
    uah = 'UAH'
    ugx = 'UGX'
    usd = 'USD'
    usn = 'USN'
    uyi = 'UYI'
    uyu = 'UYU'
    uyw = 'UYW'
    uzs = 'UZS'
    ved = 'VED'
    ves = 'VES'
    vnd = 'VND'
    vuv = 'VUV'
    wst = 'WST'
    xad = 'XAD'
    xaf = 'XAF'
    xag = 'XAG'
    xau = 'XAU'
    xba = 'XBA'
    xbb = 'XBB'
    xbc = 'XBC'
    xbd = 'XBD'
    xcd = 'XCD'
    xcg = 'XCG'
    xdr = 'XDR'
    xof = 'XOF'
    xpd = 'XPD'
    xpf = 'XPF'
    xpt = 'XPT'
    xsu = 'XSU'
    xts = 'XTS'
    xua = 'XUA'
    xxx = 'XXX'
    yer = 'YER'
    zar = 'ZAR'
    zmw = 'ZMW'
    zwg = 'ZWG'

class Feature(Enum):
    channel_viewer_extra_stats = 'channel_viewer_extra_stats'

class AlertAction(Enum):
    reload = 'reload'
    mute = 'mute'
    unmute = 'unmute'
    pause = 'pause'
    unpause = 'unpause'
    play_next = 'playNext'
    skip = 'skip'

class Error(SynchraBaseModel):
    type: str = Field(..., title='Type')
    message: str = Field(..., title='Message')
