# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class BotProvidersApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_system_bot_provider_api2_system_bot_providers_provider_delete(self, provider, **kwargs):  # noqa: E501
        """Delete System Bot Provider  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_system_bot_provider_api2_system_bot_providers_provider_delete(provider, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object provider: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_system_bot_provider_api2_system_bot_providers_provider_delete_with_http_info(provider, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_system_bot_provider_api2_system_bot_providers_provider_delete_with_http_info(provider, **kwargs)  # noqa: E501
            return data

    def delete_system_bot_provider_api2_system_bot_providers_provider_delete_with_http_info(self, provider, **kwargs):  # noqa: E501
        """Delete System Bot Provider  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_system_bot_provider_api2_system_bot_providers_provider_delete_with_http_info(provider, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object provider: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['provider']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_system_bot_provider_api2_system_bot_providers_provider_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'provider' is set
        if self.api_client.client_side_validation and ('provider' not in params or
                                                       params['provider'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `provider` when calling `delete_system_bot_provider_api2_system_bot_providers_provider_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'provider' in params:
            path_params['provider'] = params['provider']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/system-bot-providers/{provider}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_system_bot_provider_api2_system_bot_providers_provider_get(self, provider, **kwargs):  # noqa: E501
        """Get System Bot Provider  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_system_bot_provider_api2_system_bot_providers_provider_get(provider, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object provider: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_system_bot_provider_api2_system_bot_providers_provider_get_with_http_info(provider, **kwargs)  # noqa: E501
        else:
            (data) = self.get_system_bot_provider_api2_system_bot_providers_provider_get_with_http_info(provider, **kwargs)  # noqa: E501
            return data

    def get_system_bot_provider_api2_system_bot_providers_provider_get_with_http_info(self, provider, **kwargs):  # noqa: E501
        """Get System Bot Provider  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_system_bot_provider_api2_system_bot_providers_provider_get_with_http_info(provider, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object provider: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['provider']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_system_bot_provider_api2_system_bot_providers_provider_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'provider' is set
        if self.api_client.client_side_validation and ('provider' not in params or
                                                       params['provider'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `provider` when calling `get_system_bot_provider_api2_system_bot_providers_provider_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'provider' in params:
            path_params['provider'] = params['provider']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/system-bot-providers/{provider}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_system_bot_providers_api2_system_bot_providers_get(self, **kwargs):  # noqa: E501
        """Get System Bot Providers  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_system_bot_providers_api2_system_bot_providers_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_system_bot_providers_api2_system_bot_providers_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_system_bot_providers_api2_system_bot_providers_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_system_bot_providers_api2_system_bot_providers_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get System Bot Providers  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_system_bot_providers_api2_system_bot_providers_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cursor', 'per_page']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_system_bot_providers_api2_system_bot_providers_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'per_page' in params:
            query_params.append(('per_page', params['per_page']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/system-bot-providers', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
