# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ChannelQueueApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_viewer_to_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_post(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Add Viewer To Channel Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_viewer_to_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_post(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_viewer_to_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_post_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
        else:
            (data) = self.add_viewer_to_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_post_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
            return data

    def add_viewer_to_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_post_with_http_info(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Add Viewer To Channel Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_viewer_to_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_post_with_http_info(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_queue_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_viewer_to_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `add_viewer_to_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_post`")  # noqa: E501
        # verify the required parameter 'channel_queue_id' is set
        if self.api_client.client_side_validation and ('channel_queue_id' not in params or
                                                       params['channel_queue_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_queue_id` when calling `add_viewer_to_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_queue_id' in params:
            path_params['channel_queue_id'] = params['channel_queue_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues/{channel_queue_id}/viewers', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def clear_viewer_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_delete(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Clear Viewer Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.clear_viewer_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_delete(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.clear_viewer_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_delete_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
        else:
            (data) = self.clear_viewer_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_delete_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
            return data

    def clear_viewer_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_delete_with_http_info(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Clear Viewer Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.clear_viewer_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_delete_with_http_info(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_queue_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method clear_viewer_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `clear_viewer_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_delete`")  # noqa: E501
        # verify the required parameter 'channel_queue_id' is set
        if self.api_client.client_side_validation and ('channel_queue_id' not in params or
                                                       params['channel_queue_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_queue_id` when calling `clear_viewer_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_queue_id' in params:
            path_params['channel_queue_id'] = params['channel_queue_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues/{channel_queue_id}/viewers', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_queue_api2_channels_channel_id_queues_post(self, channel_id, **kwargs):  # noqa: E501
        """Create Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_queue_api2_channels_channel_id_queues_post(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_queue_api2_channels_channel_id_queues_post_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.create_queue_api2_channels_channel_id_queues_post_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def create_queue_api2_channels_channel_id_queues_post_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Create Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_queue_api2_channels_channel_id_queues_post_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_queue_api2_channels_channel_id_queues_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `create_queue_api2_channels_channel_id_queues_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_queue_api2_channels_channel_id_queues_channel_queue_id_delete(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Delete Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_queue_api2_channels_channel_id_queues_channel_queue_id_delete(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_queue_api2_channels_channel_id_queues_channel_queue_id_delete_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_queue_api2_channels_channel_id_queues_channel_queue_id_delete_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
            return data

    def delete_queue_api2_channels_channel_id_queues_channel_queue_id_delete_with_http_info(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Delete Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_queue_api2_channels_channel_id_queues_channel_queue_id_delete_with_http_info(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_queue_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_queue_api2_channels_channel_id_queues_channel_queue_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `delete_queue_api2_channels_channel_id_queues_channel_queue_id_delete`")  # noqa: E501
        # verify the required parameter 'channel_queue_id' is set
        if self.api_client.client_side_validation and ('channel_queue_id' not in params or
                                                       params['channel_queue_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_queue_id` when calling `delete_queue_api2_channels_channel_id_queues_channel_queue_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_queue_id' in params:
            path_params['channel_queue_id'] = params['channel_queue_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues/{channel_queue_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_queue_api2_channels_channel_id_queues_channel_queue_id_get(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Get Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_queue_api2_channels_channel_id_queues_channel_queue_id_get(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_queue_api2_channels_channel_id_queues_channel_queue_id_get_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_queue_api2_channels_channel_id_queues_channel_queue_id_get_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
            return data

    def get_queue_api2_channels_channel_id_queues_channel_queue_id_get_with_http_info(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Get Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_queue_api2_channels_channel_id_queues_channel_queue_id_get_with_http_info(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_queue_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_queue_api2_channels_channel_id_queues_channel_queue_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_queue_api2_channels_channel_id_queues_channel_queue_id_get`")  # noqa: E501
        # verify the required parameter 'channel_queue_id' is set
        if self.api_client.client_side_validation and ('channel_queue_id' not in params or
                                                       params['channel_queue_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_queue_id` when calling `get_queue_api2_channels_channel_id_queues_channel_queue_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_queue_id' in params:
            path_params['channel_queue_id'] = params['channel_queue_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues/{channel_queue_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_queue_viewers_api2_channels_channel_id_queues_channel_queue_id_viewers_get(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Get Queue Viewers  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_queue_viewers_api2_channels_channel_id_queues_channel_queue_id_viewers_get(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :param object provider:
        :param object provider_viewer_id:
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_queue_viewers_api2_channels_channel_id_queues_channel_queue_id_viewers_get_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_queue_viewers_api2_channels_channel_id_queues_channel_queue_id_viewers_get_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
            return data

    def get_queue_viewers_api2_channels_channel_id_queues_channel_queue_id_viewers_get_with_http_info(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Get Queue Viewers  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_queue_viewers_api2_channels_channel_id_queues_channel_queue_id_viewers_get_with_http_info(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :param object provider:
        :param object provider_viewer_id:
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_queue_id', 'provider', 'provider_viewer_id', 'cursor', 'per_page']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_queue_viewers_api2_channels_channel_id_queues_channel_queue_id_viewers_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_queue_viewers_api2_channels_channel_id_queues_channel_queue_id_viewers_get`")  # noqa: E501
        # verify the required parameter 'channel_queue_id' is set
        if self.api_client.client_side_validation and ('channel_queue_id' not in params or
                                                       params['channel_queue_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_queue_id` when calling `get_queue_viewers_api2_channels_channel_id_queues_channel_queue_id_viewers_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_queue_id' in params:
            path_params['channel_queue_id'] = params['channel_queue_id']  # noqa: E501

        query_params = []
        if 'provider' in params:
            query_params.append(('provider', params['provider']))  # noqa: E501
        if 'provider_viewer_id' in params:
            query_params.append(('provider_viewer_id', params['provider_viewer_id']))  # noqa: E501
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'per_page' in params:
            query_params.append(('per_page', params['per_page']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues/{channel_queue_id}/viewers', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_queues_api2_channels_channel_id_queues_get(self, channel_id, **kwargs):  # noqa: E501
        """Get Queues  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_queues_api2_channels_channel_id_queues_get(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_queues_api2_channels_channel_id_queues_get_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_queues_api2_channels_channel_id_queues_get_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def get_queues_api2_channels_channel_id_queues_get_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Get Queues  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_queues_api2_channels_channel_id_queues_get_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'cursor', 'per_page']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_queues_api2_channels_channel_id_queues_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_queues_api2_channels_channel_id_queues_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501

        query_params = []
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'per_page' in params:
            query_params.append(('per_page', params['per_page']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def move_viewer_to_top_of_queue_api2_channels_channel_id_queues_channel_queue_id_move_to_top_put(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Move Viewer To Top Of Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.move_viewer_to_top_of_queue_api2_channels_channel_id_queues_channel_queue_id_move_to_top_put(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.move_viewer_to_top_of_queue_api2_channels_channel_id_queues_channel_queue_id_move_to_top_put_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
        else:
            (data) = self.move_viewer_to_top_of_queue_api2_channels_channel_id_queues_channel_queue_id_move_to_top_put_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
            return data

    def move_viewer_to_top_of_queue_api2_channels_channel_id_queues_channel_queue_id_move_to_top_put_with_http_info(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Move Viewer To Top Of Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.move_viewer_to_top_of_queue_api2_channels_channel_id_queues_channel_queue_id_move_to_top_put_with_http_info(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_queue_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method move_viewer_to_top_of_queue_api2_channels_channel_id_queues_channel_queue_id_move_to_top_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `move_viewer_to_top_of_queue_api2_channels_channel_id_queues_channel_queue_id_move_to_top_put`")  # noqa: E501
        # verify the required parameter 'channel_queue_id' is set
        if self.api_client.client_side_validation and ('channel_queue_id' not in params or
                                                       params['channel_queue_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_queue_id` when calling `move_viewer_to_top_of_queue_api2_channels_channel_id_queues_channel_queue_id_move_to_top_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_queue_id' in params:
            path_params['channel_queue_id'] = params['channel_queue_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues/{channel_queue_id}/move-to-top', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete(self, channel_id, channel_queue_id, channel_queue_viewer_id, **kwargs):  # noqa: E501
        """Remove Viewer From Channel Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete(channel_id, channel_queue_id, channel_queue_viewer_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :param object channel_queue_viewer_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete_with_http_info(channel_id, channel_queue_id, channel_queue_viewer_id, **kwargs)  # noqa: E501
        else:
            (data) = self.remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete_with_http_info(channel_id, channel_queue_id, channel_queue_viewer_id, **kwargs)  # noqa: E501
            return data

    def remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete_with_http_info(self, channel_id, channel_queue_id, channel_queue_viewer_id, **kwargs):  # noqa: E501
        """Remove Viewer From Channel Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete_with_http_info(channel_id, channel_queue_id, channel_queue_viewer_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :param object channel_queue_viewer_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_queue_id', 'channel_queue_viewer_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete`")  # noqa: E501
        # verify the required parameter 'channel_queue_id' is set
        if self.api_client.client_side_validation and ('channel_queue_id' not in params or
                                                       params['channel_queue_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_queue_id` when calling `remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete`")  # noqa: E501
        # verify the required parameter 'channel_queue_viewer_id' is set
        if self.api_client.client_side_validation and ('channel_queue_viewer_id' not in params or
                                                       params['channel_queue_viewer_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_queue_viewer_id` when calling `remove_viewer_from_channel_queue_api2_channels_channel_id_queues_channel_queue_id_viewers_channel_queue_viewer_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_queue_id' in params:
            path_params['channel_queue_id'] = params['channel_queue_id']  # noqa: E501
        if 'channel_queue_viewer_id' in params:
            path_params['channel_queue_viewer_id'] = params['channel_queue_viewer_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues/{channel_queue_id}/viewers/{channel_queue_viewer_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_queue_api2_channels_channel_id_queues_channel_queue_id_put(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Update Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_queue_api2_channels_channel_id_queues_channel_queue_id_put(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_queue_api2_channels_channel_id_queues_channel_queue_id_put_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_queue_api2_channels_channel_id_queues_channel_queue_id_put_with_http_info(channel_id, channel_queue_id, **kwargs)  # noqa: E501
            return data

    def update_queue_api2_channels_channel_id_queues_channel_queue_id_put_with_http_info(self, channel_id, channel_queue_id, **kwargs):  # noqa: E501
        """Update Queue  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_queue_api2_channels_channel_id_queues_channel_queue_id_put_with_http_info(channel_id, channel_queue_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_queue_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_queue_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_queue_api2_channels_channel_id_queues_channel_queue_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `update_queue_api2_channels_channel_id_queues_channel_queue_id_put`")  # noqa: E501
        # verify the required parameter 'channel_queue_id' is set
        if self.api_client.client_side_validation and ('channel_queue_id' not in params or
                                                       params['channel_queue_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_queue_id` when calling `update_queue_api2_channels_channel_id_queues_channel_queue_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_queue_id' in params:
            path_params['channel_queue_id'] = params['channel_queue_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/queues/{channel_queue_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
