# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ChannelProviderApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_channel_provider_api2_channels_channel_id_providers_channel_provider_id_delete(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Delete Channel Provider  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_channel_provider_api2_channels_channel_id_providers_channel_provider_id_delete(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_channel_provider_api2_channels_channel_id_providers_channel_provider_id_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_channel_provider_api2_channels_channel_id_providers_channel_provider_id_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def delete_channel_provider_api2_channels_channel_id_providers_channel_provider_id_delete_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Delete Channel Provider  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_channel_provider_api2_channels_channel_id_providers_channel_provider_id_delete_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_channel_provider_api2_channels_channel_id_providers_channel_provider_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `delete_channel_provider_api2_channels_channel_id_providers_channel_provider_id_delete`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `delete_channel_provider_api2_channels_channel_id_providers_channel_provider_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/providers/{channel_provider_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def disconnect_channel_provider_bot_api2_channels_channel_id_providers_channel_provider_id_bot_delete(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Disconnect Channel Provider Bot  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.disconnect_channel_provider_bot_api2_channels_channel_id_providers_channel_provider_id_bot_delete(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.disconnect_channel_provider_bot_api2_channels_channel_id_providers_channel_provider_id_bot_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.disconnect_channel_provider_bot_api2_channels_channel_id_providers_channel_provider_id_bot_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def disconnect_channel_provider_bot_api2_channels_channel_id_providers_channel_provider_id_bot_delete_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Disconnect Channel Provider Bot  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.disconnect_channel_provider_bot_api2_channels_channel_id_providers_channel_provider_id_bot_delete_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method disconnect_channel_provider_bot_api2_channels_channel_id_providers_channel_provider_id_bot_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `disconnect_channel_provider_bot_api2_channels_channel_id_providers_channel_provider_id_bot_delete`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `disconnect_channel_provider_bot_api2_channels_channel_id_providers_channel_provider_id_bot_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/providers/{channel_provider_id}/bot', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_channel_provider_route_api2_channels_channel_id_providers_channel_provider_id_get(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Get Channel Provider Route  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_channel_provider_route_api2_channels_channel_id_providers_channel_provider_id_get(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_channel_provider_route_api2_channels_channel_id_providers_channel_provider_id_get_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_channel_provider_route_api2_channels_channel_id_providers_channel_provider_id_get_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def get_channel_provider_route_api2_channels_channel_id_providers_channel_provider_id_get_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Get Channel Provider Route  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_channel_provider_route_api2_channels_channel_id_providers_channel_provider_id_get_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_channel_provider_route_api2_channels_channel_id_providers_channel_provider_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_channel_provider_route_api2_channels_channel_id_providers_channel_provider_id_get`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `get_channel_provider_route_api2_channels_channel_id_providers_channel_provider_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/providers/{channel_provider_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_channel_providers_api2_channels_channel_id_providers_get(self, channel_id, **kwargs):  # noqa: E501
        """Get Channel Providers  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_channel_providers_api2_channels_channel_id_providers_get(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_channel_providers_api2_channels_channel_id_providers_get_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_channel_providers_api2_channels_channel_id_providers_get_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def get_channel_providers_api2_channels_channel_id_providers_get_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Get Channel Providers  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_channel_providers_api2_channels_channel_id_providers_get_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_channel_providers_api2_channels_channel_id_providers_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_channel_providers_api2_channels_channel_id_providers_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/providers', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_stream_categories_api2_stream_categories_get(self, provider, query, **kwargs):  # noqa: E501
        """Get Stream Categories  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_stream_categories_api2_stream_categories_get(provider, query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object provider: (required)
        :param object query: (required)
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_stream_categories_api2_stream_categories_get_with_http_info(provider, query, **kwargs)  # noqa: E501
        else:
            (data) = self.get_stream_categories_api2_stream_categories_get_with_http_info(provider, query, **kwargs)  # noqa: E501
            return data

    def get_stream_categories_api2_stream_categories_get_with_http_info(self, provider, query, **kwargs):  # noqa: E501
        """Get Stream Categories  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_stream_categories_api2_stream_categories_get_with_http_info(provider, query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object provider: (required)
        :param object query: (required)
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['provider', 'query', 'cursor', 'per_page']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_stream_categories_api2_stream_categories_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'provider' is set
        if self.api_client.client_side_validation and ('provider' not in params or
                                                       params['provider'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `provider` when calling `get_stream_categories_api2_stream_categories_get`")  # noqa: E501
        # verify the required parameter 'query' is set
        if self.api_client.client_side_validation and ('query' not in params or
                                                       params['query'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `query` when calling `get_stream_categories_api2_stream_categories_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'provider' in params:
            query_params.append(('provider', params['provider']))  # noqa: E501
        if 'query' in params:
            query_params.append(('query', params['query']))  # noqa: E501
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'per_page' in params:
            query_params.append(('per_page', params['per_page']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/stream-categories', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def start_commercial_api2_channels_channel_id_providers_channel_provider_id_run_commercial_post(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Start Commercial  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.start_commercial_api2_channels_channel_id_providers_channel_provider_id_run_commercial_post(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.start_commercial_api2_channels_channel_id_providers_channel_provider_id_run_commercial_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.start_commercial_api2_channels_channel_id_providers_channel_provider_id_run_commercial_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def start_commercial_api2_channels_channel_id_providers_channel_provider_id_run_commercial_post_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Start Commercial  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.start_commercial_api2_channels_channel_id_providers_channel_provider_id_run_commercial_post_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method start_commercial_api2_channels_channel_id_providers_channel_provider_id_run_commercial_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `start_commercial_api2_channels_channel_id_providers_channel_provider_id_run_commercial_post`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `start_commercial_api2_channels_channel_id_providers_channel_provider_id_run_commercial_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/providers/{channel_provider_id}/run-commercial', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_channel_provider_api2_channels_channel_id_providers_channel_provider_id_stream_put(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Update Channel Provider  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_channel_provider_api2_channels_channel_id_providers_channel_provider_id_stream_put(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_channel_provider_api2_channels_channel_id_providers_channel_provider_id_stream_put_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_channel_provider_api2_channels_channel_id_providers_channel_provider_id_stream_put_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def update_channel_provider_api2_channels_channel_id_providers_channel_provider_id_stream_put_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Update Channel Provider  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_channel_provider_api2_channels_channel_id_providers_channel_provider_id_stream_put_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_channel_provider_api2_channels_channel_id_providers_channel_provider_id_stream_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `update_channel_provider_api2_channels_channel_id_providers_channel_provider_id_stream_put`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `update_channel_provider_api2_channels_channel_id_providers_channel_provider_id_stream_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/providers/{channel_provider_id}/stream', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
