# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ChannelChatFiltersApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_post(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Create Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_post(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_post_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.create_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_post_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
            return data

    def create_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_post_with_http_info(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Create Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_post_with_http_info(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'filter_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `create_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_post`")  # noqa: E501
        # verify the required parameter 'filter_id' is set
        if self.api_client.client_side_validation and ('filter_id' not in params or
                                                       params['filter_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `filter_id` when calling `create_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'filter_id' in params:
            path_params['filter_id'] = params['filter_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters/{filter_id}/banned-terms', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_channel_filter_api2_channels_channel_id_chat_filters_post(self, channel_id, **kwargs):  # noqa: E501
        """Create Channel Filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_channel_filter_api2_channels_channel_id_chat_filters_post(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_channel_filter_api2_channels_channel_id_chat_filters_post_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.create_channel_filter_api2_channels_channel_id_chat_filters_post_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def create_channel_filter_api2_channels_channel_id_chat_filters_post_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Create Channel Filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_channel_filter_api2_channels_channel_id_chat_filters_post_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_channel_filter_api2_channels_channel_id_chat_filters_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `create_channel_filter_api2_channels_channel_id_chat_filters_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete(self, channel_id, filter_id, banned_term_id, **kwargs):  # noqa: E501
        """Delete Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete(channel_id, filter_id, banned_term_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :param object banned_term_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete_with_http_info(channel_id, filter_id, banned_term_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete_with_http_info(channel_id, filter_id, banned_term_id, **kwargs)  # noqa: E501
            return data

    def delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete_with_http_info(self, channel_id, filter_id, banned_term_id, **kwargs):  # noqa: E501
        """Delete Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete_with_http_info(channel_id, filter_id, banned_term_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :param object banned_term_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'filter_id', 'banned_term_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete`")  # noqa: E501
        # verify the required parameter 'filter_id' is set
        if self.api_client.client_side_validation and ('filter_id' not in params or
                                                       params['filter_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `filter_id` when calling `delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete`")  # noqa: E501
        # verify the required parameter 'banned_term_id' is set
        if self.api_client.client_side_validation and ('banned_term_id' not in params or
                                                       params['banned_term_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `banned_term_id` when calling `delete_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'filter_id' in params:
            path_params['filter_id'] = params['filter_id']  # noqa: E501
        if 'banned_term_id' in params:
            path_params['banned_term_id'] = params['banned_term_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters/{filter_id}/banned-terms/{banned_term_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_channel_filter_api2_channels_channel_id_chat_filters_filter_id_delete(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Delete Channel Filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_channel_filter_api2_channels_channel_id_chat_filters_filter_id_delete(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_channel_filter_api2_channels_channel_id_chat_filters_filter_id_delete_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_channel_filter_api2_channels_channel_id_chat_filters_filter_id_delete_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
            return data

    def delete_channel_filter_api2_channels_channel_id_chat_filters_filter_id_delete_with_http_info(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Delete Channel Filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_channel_filter_api2_channels_channel_id_chat_filters_filter_id_delete_with_http_info(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'filter_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_channel_filter_api2_channels_channel_id_chat_filters_filter_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `delete_channel_filter_api2_channels_channel_id_chat_filters_filter_id_delete`")  # noqa: E501
        # verify the required parameter 'filter_id' is set
        if self.api_client.client_side_validation and ('filter_id' not in params or
                                                       params['filter_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `filter_id` when calling `delete_channel_filter_api2_channels_channel_id_chat_filters_filter_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'filter_id' in params:
            path_params['filter_id'] = params['filter_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters/{filter_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get(self, channel_id, filter_id, banned_term_id, **kwargs):  # noqa: E501
        """Get Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get(channel_id, filter_id, banned_term_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :param object banned_term_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get_with_http_info(channel_id, filter_id, banned_term_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get_with_http_info(channel_id, filter_id, banned_term_id, **kwargs)  # noqa: E501
            return data

    def get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get_with_http_info(self, channel_id, filter_id, banned_term_id, **kwargs):  # noqa: E501
        """Get Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get_with_http_info(channel_id, filter_id, banned_term_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :param object banned_term_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'filter_id', 'banned_term_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get`")  # noqa: E501
        # verify the required parameter 'filter_id' is set
        if self.api_client.client_side_validation and ('filter_id' not in params or
                                                       params['filter_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `filter_id` when calling `get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get`")  # noqa: E501
        # verify the required parameter 'banned_term_id' is set
        if self.api_client.client_side_validation and ('banned_term_id' not in params or
                                                       params['banned_term_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `banned_term_id` when calling `get_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'filter_id' in params:
            path_params['filter_id'] = params['filter_id']  # noqa: E501
        if 'banned_term_id' in params:
            path_params['banned_term_id'] = params['banned_term_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters/{filter_id}/banned-terms/{banned_term_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_banned_terms_api2_channels_channel_id_chat_filters_filter_id_banned_terms_get(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Get Banned Terms  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_banned_terms_api2_channels_channel_id_chat_filters_filter_id_banned_terms_get(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_banned_terms_api2_channels_channel_id_chat_filters_filter_id_banned_terms_get_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_banned_terms_api2_channels_channel_id_chat_filters_filter_id_banned_terms_get_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
            return data

    def get_banned_terms_api2_channels_channel_id_chat_filters_filter_id_banned_terms_get_with_http_info(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Get Banned Terms  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_banned_terms_api2_channels_channel_id_chat_filters_filter_id_banned_terms_get_with_http_info(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :param object cursor:
        :param object per_page:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'filter_id', 'cursor', 'per_page']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_banned_terms_api2_channels_channel_id_chat_filters_filter_id_banned_terms_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_banned_terms_api2_channels_channel_id_chat_filters_filter_id_banned_terms_get`")  # noqa: E501
        # verify the required parameter 'filter_id' is set
        if self.api_client.client_side_validation and ('filter_id' not in params or
                                                       params['filter_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `filter_id` when calling `get_banned_terms_api2_channels_channel_id_chat_filters_filter_id_banned_terms_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'filter_id' in params:
            path_params['filter_id'] = params['filter_id']  # noqa: E501

        query_params = []
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'per_page' in params:
            query_params.append(('per_page', params['per_page']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters/{filter_id}/banned-terms', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_channel_filter_api2_channels_channel_id_chat_filters_filter_id_get(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Get Channel Filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_channel_filter_api2_channels_channel_id_chat_filters_filter_id_get(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_channel_filter_api2_channels_channel_id_chat_filters_filter_id_get_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_channel_filter_api2_channels_channel_id_chat_filters_filter_id_get_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
            return data

    def get_channel_filter_api2_channels_channel_id_chat_filters_filter_id_get_with_http_info(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Get Channel Filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_channel_filter_api2_channels_channel_id_chat_filters_filter_id_get_with_http_info(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'filter_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_channel_filter_api2_channels_channel_id_chat_filters_filter_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_channel_filter_api2_channels_channel_id_chat_filters_filter_id_get`")  # noqa: E501
        # verify the required parameter 'filter_id' is set
        if self.api_client.client_side_validation and ('filter_id' not in params or
                                                       params['filter_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `filter_id` when calling `get_channel_filter_api2_channels_channel_id_chat_filters_filter_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'filter_id' in params:
            path_params['filter_id'] = params['filter_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters/{filter_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_channel_filters_api2_channels_channel_id_chat_filters_get(self, channel_id, **kwargs):  # noqa: E501
        """Get Channel Filters  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_channel_filters_api2_channels_channel_id_chat_filters_get(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_channel_filters_api2_channels_channel_id_chat_filters_get_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_channel_filters_api2_channels_channel_id_chat_filters_get_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def get_channel_filters_api2_channels_channel_id_chat_filters_get_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Get Channel Filters  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_channel_filters_api2_channels_channel_id_chat_filters_get_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_channel_filters_api2_channels_channel_id_chat_filters_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_channel_filters_api2_channels_channel_id_chat_filters_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def test_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_test_post(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Test Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.test_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_test_post(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.test_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_test_post_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.test_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_test_post_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
            return data

    def test_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_test_post_with_http_info(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Test Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.test_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_test_post_with_http_info(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'filter_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method test_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_test_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `test_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_test_post`")  # noqa: E501
        # verify the required parameter 'filter_id' is set
        if self.api_client.client_side_validation and ('filter_id' not in params or
                                                       params['filter_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `filter_id` when calling `test_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_test_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'filter_id' in params:
            path_params['filter_id'] = params['filter_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters/{filter_id}/banned-terms/test', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put(self, channel_id, filter_id, banned_term_id, **kwargs):  # noqa: E501
        """Update Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put(channel_id, filter_id, banned_term_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :param object banned_term_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put_with_http_info(channel_id, filter_id, banned_term_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put_with_http_info(channel_id, filter_id, banned_term_id, **kwargs)  # noqa: E501
            return data

    def update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put_with_http_info(self, channel_id, filter_id, banned_term_id, **kwargs):  # noqa: E501
        """Update Banned Term  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put_with_http_info(channel_id, filter_id, banned_term_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :param object banned_term_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'filter_id', 'banned_term_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put`")  # noqa: E501
        # verify the required parameter 'filter_id' is set
        if self.api_client.client_side_validation and ('filter_id' not in params or
                                                       params['filter_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `filter_id` when calling `update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put`")  # noqa: E501
        # verify the required parameter 'banned_term_id' is set
        if self.api_client.client_side_validation and ('banned_term_id' not in params or
                                                       params['banned_term_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `banned_term_id` when calling `update_banned_term_api2_channels_channel_id_chat_filters_filter_id_banned_terms_banned_term_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'filter_id' in params:
            path_params['filter_id'] = params['filter_id']  # noqa: E501
        if 'banned_term_id' in params:
            path_params['banned_term_id'] = params['banned_term_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters/{filter_id}/banned-terms/{banned_term_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_channel_filter_api2_channels_channel_id_chat_filters_filter_id_put(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Update Channel Filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_channel_filter_api2_channels_channel_id_chat_filters_filter_id_put(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_channel_filter_api2_channels_channel_id_chat_filters_filter_id_put_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_channel_filter_api2_channels_channel_id_chat_filters_filter_id_put_with_http_info(channel_id, filter_id, **kwargs)  # noqa: E501
            return data

    def update_channel_filter_api2_channels_channel_id_chat_filters_filter_id_put_with_http_info(self, channel_id, filter_id, **kwargs):  # noqa: E501
        """Update Channel Filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_channel_filter_api2_channels_channel_id_chat_filters_filter_id_put_with_http_info(channel_id, filter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object filter_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'filter_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_channel_filter_api2_channels_channel_id_chat_filters_filter_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `update_channel_filter_api2_channels_channel_id_chat_filters_filter_id_put`")  # noqa: E501
        # verify the required parameter 'filter_id' is set
        if self.api_client.client_side_validation and ('filter_id' not in params or
                                                       params['filter_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `filter_id` when calling `update_channel_filter_api2_channels_channel_id_chat_filters_filter_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'filter_id' in params:
            path_params['filter_id'] = params['filter_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/chat-filters/{filter_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
