# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class TwitchApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_post(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Add Vip User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_post(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.add_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def add_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_post_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Add Vip User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_post_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `add_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_post`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `add_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/vips', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_post(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_post(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def ban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_post_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_post_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `ban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_post`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `ban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/ban', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_delete(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_delete(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_delete_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_delete_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_delete`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/moderators', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_post(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_post(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_post_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_post_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_post`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `ban_user_api2_channels_channel_id_twitch_channel_provider_id_moderators_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/moderators', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete(self, provider_message_id, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Delete Chat Message  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete(provider_message_id, channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object provider_message_id: (required)
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete_with_http_info(provider_message_id, channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete_with_http_info(provider_message_id, channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete_with_http_info(self, provider_message_id, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Delete Chat Message  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete_with_http_info(provider_message_id, channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object provider_message_id: (required)
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['provider_message_id', 'channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'provider_message_id' is set
        if self.api_client.client_side_validation and ('provider_message_id' not in params or
                                                       params['provider_message_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `provider_message_id` when calling `delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete`")  # noqa: E501
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `delete_chat_message_api2_channels_channel_id_twitch_channel_provider_id_chat_messages_provider_message_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'provider_message_id' in params:
            path_params['provider_message_id'] = params['provider_message_id']  # noqa: E501
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/chat-messages/{provider_message_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_raid_api2_channels_channel_id_twitch_channel_provider_id_raid_delete(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Delete Raid  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_raid_api2_channels_channel_id_twitch_channel_provider_id_raid_delete(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_raid_api2_channels_channel_id_twitch_channel_provider_id_raid_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_raid_api2_channels_channel_id_twitch_channel_provider_id_raid_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def delete_raid_api2_channels_channel_id_twitch_channel_provider_id_raid_delete_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Delete Raid  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_raid_api2_channels_channel_id_twitch_channel_provider_id_raid_delete_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_raid_api2_channels_channel_id_twitch_channel_provider_id_raid_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `delete_raid_api2_channels_channel_id_twitch_channel_provider_id_raid_delete`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `delete_raid_api2_channels_channel_id_twitch_channel_provider_id_raid_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/raid', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def emulate_automatic_reward_redemption_api2_twitch_eventsub_emulate_automatic_reward_redemption_post(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Automatic Reward Redemption  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_automatic_reward_redemption_api2_twitch_eventsub_emulate_automatic_reward_redemption_post(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.emulate_automatic_reward_redemption_api2_twitch_eventsub_emulate_automatic_reward_redemption_post_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.emulate_automatic_reward_redemption_api2_twitch_eventsub_emulate_automatic_reward_redemption_post_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def emulate_automatic_reward_redemption_api2_twitch_eventsub_emulate_automatic_reward_redemption_post_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Automatic Reward Redemption  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_automatic_reward_redemption_api2_twitch_eventsub_emulate_automatic_reward_redemption_post_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method emulate_automatic_reward_redemption_api2_twitch_eventsub_emulate_automatic_reward_redemption_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `emulate_automatic_reward_redemption_api2_twitch_eventsub_emulate_automatic_reward_redemption_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'channel_id' in params:
            query_params.append(('channel_id', params['channel_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/twitch/eventsub/emulate-automatic-reward-redemption', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def emulate_channel_chat_message_api2_twitch_eventsub_emulate_channel_chat_message_post(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Channel Chat Message  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_channel_chat_message_api2_twitch_eventsub_emulate_channel_chat_message_post(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.emulate_channel_chat_message_api2_twitch_eventsub_emulate_channel_chat_message_post_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.emulate_channel_chat_message_api2_twitch_eventsub_emulate_channel_chat_message_post_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def emulate_channel_chat_message_api2_twitch_eventsub_emulate_channel_chat_message_post_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Channel Chat Message  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_channel_chat_message_api2_twitch_eventsub_emulate_channel_chat_message_post_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method emulate_channel_chat_message_api2_twitch_eventsub_emulate_channel_chat_message_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `emulate_channel_chat_message_api2_twitch_eventsub_emulate_channel_chat_message_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'channel_id' in params:
            query_params.append(('channel_id', params['channel_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/twitch/eventsub/emulate-channel-chat-message', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def emulate_cheer_api2_twitch_eventsub_emulate_cheer_post(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Cheer  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_cheer_api2_twitch_eventsub_emulate_cheer_post(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.emulate_cheer_api2_twitch_eventsub_emulate_cheer_post_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.emulate_cheer_api2_twitch_eventsub_emulate_cheer_post_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def emulate_cheer_api2_twitch_eventsub_emulate_cheer_post_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Cheer  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_cheer_api2_twitch_eventsub_emulate_cheer_post_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method emulate_cheer_api2_twitch_eventsub_emulate_cheer_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `emulate_cheer_api2_twitch_eventsub_emulate_cheer_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'channel_id' in params:
            query_params.append(('channel_id', params['channel_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/twitch/eventsub/emulate-cheer', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def emulate_custom_reward_redemption_api2_twitch_eventsub_emulate_custom_reward_redemption_post(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Custom Reward Redemption  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_custom_reward_redemption_api2_twitch_eventsub_emulate_custom_reward_redemption_post(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.emulate_custom_reward_redemption_api2_twitch_eventsub_emulate_custom_reward_redemption_post_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.emulate_custom_reward_redemption_api2_twitch_eventsub_emulate_custom_reward_redemption_post_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def emulate_custom_reward_redemption_api2_twitch_eventsub_emulate_custom_reward_redemption_post_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Custom Reward Redemption  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_custom_reward_redemption_api2_twitch_eventsub_emulate_custom_reward_redemption_post_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method emulate_custom_reward_redemption_api2_twitch_eventsub_emulate_custom_reward_redemption_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `emulate_custom_reward_redemption_api2_twitch_eventsub_emulate_custom_reward_redemption_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'channel_id' in params:
            query_params.append(('channel_id', params['channel_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/twitch/eventsub/emulate-custom-reward-redemption', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def emulate_subscription_api2_twitch_eventsub_emulate_subscription_post(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Subscription  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_subscription_api2_twitch_eventsub_emulate_subscription_post(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.emulate_subscription_api2_twitch_eventsub_emulate_subscription_post_with_http_info(channel_id, **kwargs)  # noqa: E501
        else:
            (data) = self.emulate_subscription_api2_twitch_eventsub_emulate_subscription_post_with_http_info(channel_id, **kwargs)  # noqa: E501
            return data

    def emulate_subscription_api2_twitch_eventsub_emulate_subscription_post_with_http_info(self, channel_id, **kwargs):  # noqa: E501
        """Emulate Subscription  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.emulate_subscription_api2_twitch_eventsub_emulate_subscription_post_with_http_info(channel_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method emulate_subscription_api2_twitch_eventsub_emulate_subscription_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `emulate_subscription_api2_twitch_eventsub_emulate_subscription_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'channel_id' in params:
            query_params.append(('channel_id', params['channel_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/twitch/eventsub/emulate-subscription', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_moderators_api2_channels_channel_id_twitch_channel_provider_id_moderators_get(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Get Moderators  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_moderators_api2_channels_channel_id_twitch_channel_provider_id_moderators_get(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_moderators_api2_channels_channel_id_twitch_channel_provider_id_moderators_get_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_moderators_api2_channels_channel_id_twitch_channel_provider_id_moderators_get_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def get_moderators_api2_channels_channel_id_twitch_channel_provider_id_moderators_get_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Get Moderators  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_moderators_api2_channels_channel_id_twitch_channel_provider_id_moderators_get_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_moderators_api2_channels_channel_id_twitch_channel_provider_id_moderators_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_moderators_api2_channels_channel_id_twitch_channel_provider_id_moderators_get`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `get_moderators_api2_channels_channel_id_twitch_channel_provider_id_moderators_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/moderators', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get(self, channel_id, provider_channel_id, id, size, **kwargs):  # noqa: E501
        """Get Twitch Badge Image  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get(channel_id, provider_channel_id, id, size, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object provider_channel_id: (required)
        :param object id: Format: {set_id}-{id} (required)
        :param object size: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get_with_http_info(channel_id, provider_channel_id, id, size, **kwargs)  # noqa: E501
        else:
            (data) = self.get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get_with_http_info(channel_id, provider_channel_id, id, size, **kwargs)  # noqa: E501
            return data

    def get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get_with_http_info(self, channel_id, provider_channel_id, id, size, **kwargs):  # noqa: E501
        """Get Twitch Badge Image  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get_with_http_info(channel_id, provider_channel_id, id, size, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object provider_channel_id: (required)
        :param object id: Format: {set_id}-{id} (required)
        :param object size: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'provider_channel_id', 'id', 'size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get`")  # noqa: E501
        # verify the required parameter 'provider_channel_id' is set
        if self.api_client.client_side_validation and ('provider_channel_id' not in params or
                                                       params['provider_channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `provider_channel_id` when calling `get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get`")  # noqa: E501
        # verify the required parameter 'id' is set
        if self.api_client.client_side_validation and ('id' not in params or
                                                       params['id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `id` when calling `get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get`")  # noqa: E501
        # verify the required parameter 'size' is set
        if self.api_client.client_side_validation and ('size' not in params or
                                                       params['size'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `size` when calling `get_twitch_badge_image_api2_channels_channel_id_twitch_badge_image_provider_channel_id_size_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'provider_channel_id' in params:
            path_params['provider_channel_id'] = params['provider_channel_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'size' in params:
            path_params['size'] = params['size']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/badge-image/{provider_channel_id}/{size}/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_vip_users_api2_channels_channel_id_twitch_channel_provider_id_vips_get(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Get Vip Users  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_vip_users_api2_channels_channel_id_twitch_channel_provider_id_vips_get(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_vip_users_api2_channels_channel_id_twitch_channel_provider_id_vips_get_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_vip_users_api2_channels_channel_id_twitch_channel_provider_id_vips_get_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def get_vip_users_api2_channels_channel_id_twitch_channel_provider_id_vips_get_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Get Vip Users  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_vip_users_api2_channels_channel_id_twitch_channel_provider_id_vips_get_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_vip_users_api2_channels_channel_id_twitch_channel_provider_id_vips_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_vip_users_api2_channels_channel_id_twitch_channel_provider_id_vips_get`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `get_vip_users_api2_channels_channel_id_twitch_channel_provider_id_vips_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/vips', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def raid_channel_api2_channels_channel_id_twitch_channel_provider_id_raid_post(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Raid Channel  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.raid_channel_api2_channels_channel_id_twitch_channel_provider_id_raid_post(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.raid_channel_api2_channels_channel_id_twitch_channel_provider_id_raid_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.raid_channel_api2_channels_channel_id_twitch_channel_provider_id_raid_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def raid_channel_api2_channels_channel_id_twitch_channel_provider_id_raid_post_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Raid Channel  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.raid_channel_api2_channels_channel_id_twitch_channel_provider_id_raid_post_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method raid_channel_api2_channels_channel_id_twitch_channel_provider_id_raid_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `raid_channel_api2_channels_channel_id_twitch_channel_provider_id_raid_post`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `raid_channel_api2_channels_channel_id_twitch_channel_provider_id_raid_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/raid', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remove_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_delete(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Remove Vip User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_delete(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.remove_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.remove_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def remove_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_delete_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Remove Vip User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_delete_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remove_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `remove_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_delete`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `remove_vip_user_api2_channels_channel_id_twitch_channel_provider_id_vips_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/vips', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def shoutout_user_api2_channels_channel_id_twitch_channel_provider_id_shoutout_post(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Shoutout User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.shoutout_user_api2_channels_channel_id_twitch_channel_provider_id_shoutout_post(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.shoutout_user_api2_channels_channel_id_twitch_channel_provider_id_shoutout_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.shoutout_user_api2_channels_channel_id_twitch_channel_provider_id_shoutout_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def shoutout_user_api2_channels_channel_id_twitch_channel_provider_id_shoutout_post_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Shoutout User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.shoutout_user_api2_channels_channel_id_twitch_channel_provider_id_shoutout_post_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method shoutout_user_api2_channels_channel_id_twitch_channel_provider_id_shoutout_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `shoutout_user_api2_channels_channel_id_twitch_channel_provider_id_shoutout_post`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `shoutout_user_api2_channels_channel_id_twitch_channel_provider_id_shoutout_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/shoutout', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete(self, channel_id, channel_provider_id, provider_viewer_id, **kwargs):  # noqa: E501
        """Unban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete(channel_id, channel_provider_id, provider_viewer_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :param object provider_viewer_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete_with_http_info(channel_id, channel_provider_id, provider_viewer_id, **kwargs)  # noqa: E501
        else:
            (data) = self.unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete_with_http_info(channel_id, channel_provider_id, provider_viewer_id, **kwargs)  # noqa: E501
            return data

    def unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete_with_http_info(self, channel_id, channel_provider_id, provider_viewer_id, **kwargs):  # noqa: E501
        """Unban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete_with_http_info(channel_id, channel_provider_id, provider_viewer_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :param object provider_viewer_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id', 'provider_viewer_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete`")  # noqa: E501
        # verify the required parameter 'provider_viewer_id' is set
        if self.api_client.client_side_validation and ('provider_viewer_id' not in params or
                                                       params['provider_viewer_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `provider_viewer_id` when calling `unban_user_api2_channels_channel_id_twitch_channel_provider_id_ban_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []
        if 'provider_viewer_id' in params:
            query_params.append(('provider_viewer_id', params['provider_viewer_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/twitch/{channel_provider_id}/ban', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
