# coding: utf-8

"""
    Synchra API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class YouTubeApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def ban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_post(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_post(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def ban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_post_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_post_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `ban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_post`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `ban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/youtube/{channel_provider_id}/ban', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_delete(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_delete(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_delete_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_delete_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_delete_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_delete`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/youtube/{channel_provider_id}/moderators', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_post(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_post(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_post_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Ban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_post_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_post`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `ban_user_api2_channels_channel_id_youtube_channel_provider_id_moderators_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/youtube/{channel_provider_id}/moderators', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_moderators_api2_channels_channel_id_youtube_channel_provider_id_moderators_get(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Get Moderators  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_moderators_api2_channels_channel_id_youtube_channel_provider_id_moderators_get(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_moderators_api2_channels_channel_id_youtube_channel_provider_id_moderators_get_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_moderators_api2_channels_channel_id_youtube_channel_provider_id_moderators_get_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def get_moderators_api2_channels_channel_id_youtube_channel_provider_id_moderators_get_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Get Moderators  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_moderators_api2_channels_channel_id_youtube_channel_provider_id_moderators_get_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_moderators_api2_channels_channel_id_youtube_channel_provider_id_moderators_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `get_moderators_api2_channels_channel_id_youtube_channel_provider_id_moderators_get`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `get_moderators_api2_channels_channel_id_youtube_channel_provider_id_moderators_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/youtube/{channel_provider_id}/moderators', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete(self, channel_id, channel_provider_id, provider_viewer_id, **kwargs):  # noqa: E501
        """Unban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete(channel_id, channel_provider_id, provider_viewer_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :param object provider_viewer_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete_with_http_info(channel_id, channel_provider_id, provider_viewer_id, **kwargs)  # noqa: E501
        else:
            (data) = self.unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete_with_http_info(channel_id, channel_provider_id, provider_viewer_id, **kwargs)  # noqa: E501
            return data

    def unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete_with_http_info(self, channel_id, channel_provider_id, provider_viewer_id, **kwargs):  # noqa: E501
        """Unban User  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete_with_http_info(channel_id, channel_provider_id, provider_viewer_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :param object provider_viewer_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id', 'provider_viewer_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete`")  # noqa: E501
        # verify the required parameter 'provider_viewer_id' is set
        if self.api_client.client_side_validation and ('provider_viewer_id' not in params or
                                                       params['provider_viewer_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `provider_viewer_id` when calling `unban_user_api2_channels_channel_id_youtube_channel_provider_id_ban_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []
        if 'provider_viewer_id' in params:
            query_params.append(('provider_viewer_id', params['provider_viewer_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/youtube/{channel_provider_id}/ban', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def youtube_create_broadcast_route_api2_channels_channel_id_providers_channel_provider_id_youtube_broadcast_post(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Youtube Create Broadcast Route  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.youtube_create_broadcast_route_api2_channels_channel_id_providers_channel_provider_id_youtube_broadcast_post(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.youtube_create_broadcast_route_api2_channels_channel_id_providers_channel_provider_id_youtube_broadcast_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
        else:
            (data) = self.youtube_create_broadcast_route_api2_channels_channel_id_providers_channel_provider_id_youtube_broadcast_post_with_http_info(channel_id, channel_provider_id, **kwargs)  # noqa: E501
            return data

    def youtube_create_broadcast_route_api2_channels_channel_id_providers_channel_provider_id_youtube_broadcast_post_with_http_info(self, channel_id, channel_provider_id, **kwargs):  # noqa: E501
        """Youtube Create Broadcast Route  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.youtube_create_broadcast_route_api2_channels_channel_id_providers_channel_provider_id_youtube_broadcast_post_with_http_info(channel_id, channel_provider_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object channel_id: (required)
        :param object channel_provider_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['channel_id', 'channel_provider_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method youtube_create_broadcast_route_api2_channels_channel_id_providers_channel_provider_id_youtube_broadcast_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'channel_id' is set
        if self.api_client.client_side_validation and ('channel_id' not in params or
                                                       params['channel_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_id` when calling `youtube_create_broadcast_route_api2_channels_channel_id_providers_channel_provider_id_youtube_broadcast_post`")  # noqa: E501
        # verify the required parameter 'channel_provider_id' is set
        if self.api_client.client_side_validation and ('channel_provider_id' not in params or
                                                       params['channel_provider_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `channel_provider_id` when calling `youtube_create_broadcast_route_api2_channels_channel_id_providers_channel_provider_id_youtube_broadcast_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'channel_id' in params:
            path_params['channel_id'] = params['channel_id']  # noqa: E501
        if 'channel_provider_id' in params:
            path_params['channel_provider_id'] = params['channel_provider_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/2/channels/{channel_id}/providers/{channel_provider_id}/youtube/broadcast', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
